function Grafipro3(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data
 
%  Auto-generated by MATLAB on 14-Feb-2020 20:43:02
 
% Create figure
figure1 = figure('NumberTitle','off','Name','Grafipro2');
 
% Create axes
axes1 = axes('Parent',figure1,...
'Position',[0.13 0.11 0.775 0.801904761904762]);
hold(axes1,'on');
 
% Create plot
plot(X1,Y1,'LineWidth',3,...
'Color',[0.164705887436867 0.384313732385635 0.274509817361832]);
 
% Create ylabel
ylabel('f(t)','FontName','Arial');
 
% Create xlabel
xlabel('t','FontName','Arial');
 
% Create title
title('GRÁFICA FASE FUNCIÓN 3');
 
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-5 5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-13 12]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.937254905700684 0.866666674613953 0.866666674613953],...
'FontName','Arial','XAxisLocation','origin','XColor',...
[0.600000023841858 0.200000002980232 0],'XGrid','on','XTick',...
[-10 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8],'XTickLabel',...
{'','-8','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
'YAxisLocation','origin','YColor',[0.600000023841858 0.200000002980232 0],...
'YGrid','on','YTick',[-12 -10 -8 -6 -4 -2 0 2 4 6 8 10],'YTickLabel',...
{'-12','-10','-8','-6','-4','-2','','2','4','6','8','10'},'ZColor',...
[0.600000023841858 0.200000002980232 0]);
