function Grafipro1(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data
 
%  Auto-generated by MATLAB on 14-Feb-2020 17:48:52
 
% Create figure
figure1 = figure('NumberTitle','off','Name','Grafipro2');
 
% Create axes
axes1 = axes('Parent',figure1,...
'Position',[0.13 0.11 0.775 0.801904761904762]);
hold(axes1,'on');
 
% Create plot
plot(X1,Y1,'LineWidth',3,'Color',[0.749019622802734 0.749019622802734 0]);
 
% Create ylabel
ylabel('x(t)','FontName','Arial');
 
% Create xlabel
xlabel('t','FontName','Arial');
 
% Create title
%title('GRÁFICA PROBLEMA 2');
 
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[-7 7]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-2 6]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.960784316062927 0.976470589637756 0.992156863212585],...
'FontName','Arial','XAxisLocation','origin','XColor',...
[0.152941182255745 0.227450981736183 0.372549027204514],'XGrid','on',...
'XTick',[-10 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8],'XTickLabel',...
{'','-8','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7',''},...
'YAxisLocation','origin','YColor',...
[0.152941182255745 0.227450981736183 0.372549027204514],'YGrid','on',...
'YTick',[-5 -4 -3 -2 -1 0 1 2 3 4 5 10],'YTickLabel',...
{'-5','-4','-3','-2','-1','','1','2','3','4','5',''},'ZColor',...
[0.152941182255745 0.227450981736183 0.372549027204514]);
